# Generated by Django 5.1 on 2024-08-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_alter_song_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
